"""add tables 3

Revision ID: 29be7d1a329c
Revises: d752954a5e7e
Create Date: 2026-07-13 09:58:16.527059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29be7d1a329c'
down_revision: Union[str, Sequence[str], None] = 'd752954a5e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_channels',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('recipient_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('is_pending', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['recipient_tg_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'recipient_tg_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_channels')
    # ### end Alembic commands ###
