"""separete invitations table

Revision ID: 315ce28452cd
Revises: f554869b272c
Create Date: 2026-07-21 10:13:25.097934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '315ce28452cd'
down_revision: Union[str, Sequence[str], None] = 'f554869b272c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('worker', 'customer', name='invitationrole'), nullable=False),
    sa.Column('secret_key', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_order_id'), 'invitations', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitations_order_id'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
