"""add title to order

Revision ID: 643793bdbbd8
Revises: 8d6c276d4e1b
Create Date: 2026-07-09 02:40:04.554238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643793bdbbd8'
down_revision: Union[str, Sequence[str], None] = '8d6c276d4e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'title')
    # ### end Alembic commands ###
