"""add chat_id to user

Revision ID: 8d6c276d4e1b
Revises: e86438e4c481
Create Date: 2026-07-08 18:29:41.656089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6c276d4e1b'
down_revision: Union[str, Sequence[str], None] = 'e86438e4c481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_chat_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tg_chat_id')
    # ### end Alembic commands ###
