"""make cascade deletion for notification-order relationship

Revision ID: af955e6f5f81
Revises: 29be7d1a329c
Create Date: 2026-07-19 07:30:11.854482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af955e6f5f81'
down_revision: Union[str, Sequence[str], None] = '29be7d1a329c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notification_channels_order_id_fkey'), 'notification_channels', type_='foreignkey')
    op.create_foreign_key(None, 'notification_channels', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification_channels', type_='foreignkey')
    op.create_foreign_key(op.f('notification_channels_order_id_fkey'), 'notification_channels', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
