"""initial

Revision ID: e86438e4c481
Revises: 
Create Date: 2026-07-08 17:10:17.780947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86438e4c481'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.create_table('managers_workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('worker_tg_id', sa.BigInteger(), nullable=True),
    sa.Column('saved_name', sa.String(), nullable=False),
    sa.Column('tg_username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['manager_tg_id'], ['users.tg_id'], ),
    sa.ForeignKeyConstraint(['worker_tg_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('worker_tg_id', sa.BigInteger(), nullable=True),
    sa.Column('customer_tg_id', sa.BigInteger(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paycheck', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('created', 'completed', 'cancelled', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_tg_id'], ['users.tg_id'], ),
    sa.ForeignKeyConstraint(['manager_tg_id'], ['users.tg_id'], ),
    sa.ForeignKeyConstraint(['worker_tg_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('sender_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['sender_tg_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('orders')
    op.drop_table('managers_workers')
    op.drop_table('users')
    # ### end Alembic commands ###
